
<div style="float:left; width:20%;">
	<ul class="nav nav-pills nav-stacked">
		<li><a href="codegenerator/createmodule">Module Generator</a></li>
	</ul>
</div>

<div style="float:right; width:78%;">
	<div>
		<h2>Welcome to Zend Framework Code Generator!</h2>
	</div>
	<br/><br/>
	<p>
		You may use the following generators to quickly build up your ZF2 application:
		
		<ul>
			<li><a href="codegenerator/createmodule">Module Generator</a></li>
		</ul>
		<br/>
		Other code generators will be available in the future:<br/>
		<br/>
		<ul>
			<li>Controller Generator</li>
			<li>Form Generator</li>
			<li>Model Generator</li>
		</ul>
	</p>
</div>

<div style="clear:both;">
</div>

